[package]
name = "deep_filter"
version = "0.5.7-pre"
authors = ["tonari & Hendrik Schröter"]
edition = "2021"
description = "Noise suppression using deep filtering"
repository = "https://github.com/tonarino/DeepFilterNet"
license = "MIT/Apache-2.0"
publish = false
rust-version = "1.91"

[[bin]]
name = "deep-filter"
path = "src/bin/deep-filter.rs"

[[bin]]
name = "enhance-wav"
path = "src/bin/enhance_wav.rs"

[dependencies]
anyhow = "1"
flate2 = "1"
hound = "3.5"
itertools = "0.10"
log = { version = "0.4", features = ["std"] }

ndarray = "^0.17"
num-complex = { version = "^0.4", features = ["serde"] }
realfft = "^3.5"
rust-ini = "^0.21"
rustfft = "^6.4"
tar = "^0.4"
tract-core = "^0.23"
tract-hir = "^0.23"
tract-onnx = "^0.23"
tract-pulse = "^0.23"

[dev-dependencies]
rand = "^0.8"
